sudo: required
dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install tox-travis

script:
  - tox

after_success:
  - tox -e coverage,codecov

deploy:
  - provider: pypi
    user: zsimic
    password:
      secure: "IYnTSp0aaT2GdehMB1eC0XzUuc7kple35IvxnLnxUsWo+ys9ISZ8ft8XC5NOPaEthXo2HAsbTzIg+gVF62/KBk9yoYGWKz3nLfO7BPEA3lX8Z7GYJWqsMKp3tWzoW0RnmxHmCr1jQwHefowgxnCE+4NqCnbZclUQv0FXOL17d52h8iFIwhOHYswcaoOJ4qui86z7sKemDNFfqvgTKMt3L57JVi/qBMtZ0p3Rk7hqySW+AT3e01kBeRF+c+R70m31+jhr+Ncd1ZvZTPwioVGTR5qXOXlltp2b+hrN6y8ynElkO1gC9EEn9DkQomwnKJg6zv5RJcgB9gi+W7njhBRCfaZtE/C01Door0JS+lw7v4l23MkZ3UWuCWtgrFvfvX9Oa+1Rs7penkK+CB24ayzzhHuRA9mUdRqLc9beBgRFyMDa8g/O7CGgTTmbrRUGmuqSbWyqj7P/Fe8lcDwY5YILiWs4d1mWzkZESiTtKTpQZ2p+IWRMRO2azhA0Z6vvcnuE1ipaKS8R2gUvaconHpq4jNGw187goXQfEtymb9a8yJ3iOMFctPxwbCoUv66u3U1GxWkp1GHObsKkgIGOhQpxjY5SC4gW85+5jmNKv3qEPFrbIdwxQcrmFdeIee1GxiTNJG1/4MYKuFRGmnI2aIdc2BuIuNm/n9rtevmqDPpM+YM="
    distributions: "sdist bdist_wheel --universal"
    on:
      python: 3.7
      repo: zsimic/runez
      tags: true
